### ISSUE TITLE
Question: How can I use the code for other datasets

### ISSUE THREAD

**Issue by pedramkho** [vita-epfl/trajnetplusplusdataset#1]

**Comment by theDebugger811** [comment]
Hello,
     The explanation has been added to the README which explains the dataset conversion process.
To use the code for other datasets, all you need to do is: Add the function to readers.py that converts the raw data of the dataset into corresponding TrackRows. Subsequently, call this added function in convert.py

Later, the scene.rows_to_file function (which is called by convert.py) will automatically prepare the corresponding scenes (SceneRows) given the obtained TrackRows. Finally, the obtained scenes will be categorized with the help of trajectory_type.
For details regarding the attributes for scene preparation and scene categorization, run
python -m trajnetdataset.convert --help

**Comment by pedramkho** [comment]
Thank you for your answer.

**Comment by theDebugger811** [comment]
You can refer here for a detailed explanation: https://thedebugger811.github.io/posts/2020/10/data_conversion/
