### ISSUE TITLE
How to generate SDD to be TrajNet format?

### ISSUE THREAD

**Issue by sff1019** [vita-epfl/trajnetplusplusdataset#10]
Hi, first of all thank you for this amazing work! 
I was looking into your repository and found that the SDD you have here have very different values from the raw dataset (e.g., x and y values are much smaller, pedestrian ids are different, etc.). 
Is there a way to generate your version of SDD using this repository? I would like to generate validation and test data.

**Comment by theDebugger811** [comment]
Hi,
    We have kept the SDD dataset for legacy purposes. We do not use it in TrajNet++. 

However, if you would like to convert SDD or any external dataset, please do refer to this [link](https://thedebugger811.github.io/posts/2020/10/data_conversion/)

Hope this helps!
