### ISSUE TITLE
Issue with obs and pred length

### ISSUE THREAD

**Issue by pedramkho** [vita-epfl/trajnetplusplusdataset#3]
I'm using the code to convert hotel dataset with obs_length: 9 and pred_length:12 as setting. But checking tha jasons, each scene contains 200 frames (and not of 21).

**Comment by theDebugger811** [comment]
Hello,
     This is because in the original dataset the frames are numbered as a multiple of 10. i.e. Frame 0, Frame 10... Frame 200 (21 frames!). So, the length of frames is (obs_length + pred_length - 1)*diff_between_consec_frames.

Thanks
Parth
