### ISSUE TITLE
Is there a way to change the pedestrian speed range for the model ? 

### ISSUE THREAD

**Issue by valavakilian** [vita-epfl/trajnetplusplusdataset#4]
Is there an easy way to provide a range of speeds for the synthetic data generation ?

**Comment by theDebugger811** [comment]
Hello,  
     You can manually set the speed for synthetic data generation [here](https://github.com/vita-epfl/trajnetplusplusdataset/blob/6364550049d12336ef077dc12c1b9721f2182af5/trajnetdataset/controlled_data.py#L68)
