### ISSUE TITLE
Questions about converting the external data

### ISSUE THREAD

**Issue by chenrxi** [vita-epfl/trajnetplusplusdataset#9]
I am new to trajectory prediction.  I want to convert my data to the format like ucy/eth dataset. Their original solution is about 700 * 500, how can they transform to <f, p, x, y> . I have a question whether I can normalize the coordinate by using your code? To normalize the speed or distance between each pedestrian.

**Comment by theDebugger811** [comment]
Hello,
     Specific to the UCY conversion: You can look at the conversion formula [here](https://github.com/vita-epfl/trajnetplusplusdataset/blob/6364550049d12336ef077dc12c1b9721f2182af5/trajnetdataset/readers.py#L44)
You can do extra tricks on UCY like normalization by editing the conversion formula.

Further, if you want to convert external datasets from <f, p, x, y> to trajnet++ format. Please refer to this [blog](https://thedebugger811.github.io/posts/2020/10/data_conversion/). 

Feel free to close the issue if it addresses your concern.
